# Generated by Django 5.2.7 on 2025-10-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="sku",
            options={"verbose_name_plural": "SKUs"},
        ),
    ]
